version: '3'
services:
  unbound:
    image: klutchell/unbound
    container_name: unbound
    cap_add:
      - NET_ADMIN
    network_mode: host
    # ports:
    #  - "53:53"
    #  - "53:53/udp"
    volumes:
      - ./config:/opt/unbound/etc/unbound/
    restart: unless-stopped
